export type LegalSection = { heading: string; paragraphs?: string[]; bullets?: string[] };
export type LegalPageContent = { language: 'de' | 'en'; label: string; title: string; intro: string; updated: string; alternateHref: string; alternateLabel: string; sections: LegalSection[] };

const operatorDe: LegalSection = {
  heading: 'Anbieter',
  paragraphs: ['Xsigns GmbH & Co. KG', 'Clärenore-Stinnes-Straße 15 · 27283 Verden (Aller) · Deutschland', 'Telefon: +49 4231 9033900 · E-Mail: info@xsigns.de'],
};
const operatorEn: LegalSection = {
  heading: 'Provider',
  paragraphs: ['Xsigns GmbH & Co. KG', 'Clärenore-Stinnes-Straße 15 · 27283 Verden (Aller) · Germany', 'Phone: +49 4231 9033900 · Email: info@xsigns.de'],
};

export const legalContent: Record<string, LegalPageContent> = {
  imprintDe: { language:'de', label:'Rechtliches', title:'Impressum', intro:'Angaben gemäß den gesetzlichen Informationspflichten.', updated:'Stand: September 2026', alternateHref:'/en/imprint', alternateLabel:'EN', sections:[
    operatorDe,
    { heading:'Register und Vertretung', paragraphs:['Handelsregister: Amtsgericht Walsrode, HRA 200556', 'Umsatzsteuer-Identifikationsnummer: DE258006068', 'Persönlich haftende Gesellschafterin: Xsigns Verwaltungs GmbH · Amtsgericht Walsrode, HRB 200957', 'Geschäftsführer: André Litfin und Maximilian Fixl'] },
    { heading:'Inhaltliche Verantwortung', paragraphs:['Verantwortlich für den Inhalt dieser Website ist die Xsigns GmbH & Co. KG, vertreten durch ihre Geschäftsführer.'] },
    { heading:'Hinweise zu externen Links', paragraphs:['Für Inhalte verlinkter externer Websites sind ausschließlich deren Betreiber verantwortlich. Bei Bekanntwerden einer Rechtsverletzung entfernen wir den betreffenden Link.'] },
  ]},
  imprintEn: { language:'en', label:'Legal', title:'Imprint', intro:'Provider information in accordance with German legal requirements.', updated:'Last updated: September 2026', alternateHref:'/impressum', alternateLabel:'DE', sections:[
    operatorEn,
    { heading:'Registration and representation', paragraphs:['Commercial register: Local Court of Walsrode, HRA 200556', 'VAT identification number: DE258006068', 'General partner: Xsigns Verwaltungs GmbH · Local Court of Walsrode, HRB 200957', 'Managing directors: André Litfin and Maximilian Fixl'] },
    { heading:'Responsibility for content', paragraphs:['Xsigns GmbH & Co. KG, represented by its managing directors, is responsible for the content of this website.'] },
    { heading:'External links', paragraphs:['External website operators are solely responsible for their content. We remove links when we become aware of a legal infringement.'] },
  ]},
  privacyDe: { language:'de', label:'Datenschutz', title:'Datenschutzerklärung', intro:'Hier erklären wir verständlich, welche Daten Oseyro verarbeitet und wie Sie Ihre Rechte ausüben können.', updated:'Stand: September 2026', alternateHref:'/en/privacy', alternateLabel:'EN', sections:[
    { heading:'1. Verantwortlicher', paragraphs:['Verantwortlicher im Sinne der Datenschutz-Grundverordnung ist:', 'Xsigns GmbH & Co. KG · Clärenore-Stinnes-Straße 15 · 27283 Verden (Aller) · Deutschland', 'E-Mail: info@xsigns.de · Telefon: +49 4231 9033900'] },
    { heading:'2. Aufruf dieser Website', paragraphs:['Beim Aufruf von oseyro.com verarbeitet unser Hosting-System technisch erforderliche Protokolldaten. Dazu können IP-Adresse, Zeitpunkt, aufgerufene Adresse, übertragene Datenmenge, Referrer, Browser und Betriebssystem gehören. Die Verarbeitung dient der sicheren und stabilen Bereitstellung nach Art. 6 Abs. 1 lit. f DSGVO.', 'Die öffentliche Website verwendet derzeit keine Analyse- oder Werbedienste und setzt keine Marketing-Cookies. Technisch erforderliche Schutz- und Auslieferungsfunktionen bleiben hiervon unberührt.'] },
    { heading:'3. Kontakt', paragraphs:['Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre Kontaktdaten und den Inhalt Ihrer Anfrage, um diese zu beantworten. Rechtsgrundlage ist je nach Anliegen Art. 6 Abs. 1 lit. b oder f DSGVO.'] },
    { heading:'4. Nutzung von Oseyro', paragraphs:['Bei der Nutzung einer Oseyro-Umgebung verarbeiten wir die für Anmeldung, Kundenservice, Aufgaben, Kalender, Zusammenarbeit, Sicherheit und Nachweisführung erforderlichen Konto-, Organisations-, Kommunikations- und Nutzungsdaten. Welche Inhalte verarbeitet werden, bestimmt der jeweilige Kunde als Betreiber seiner Umgebung. Xsigns verarbeitet diese Daten im Regelfall als Auftragsverarbeiter nach dessen Weisungen.', 'Zugriffe werden rollenbasiert begrenzt. Private Bereiche, persönliche Postfächer und private Kalenderinhalte werden nur den jeweils berechtigten Personen vollständig angezeigt.'] },
    { heading:'5. Google-Nutzerdaten', paragraphs:['Eine Verbindung mit Google ist freiwillig und wird von jedem Benutzer für das eigene Google-Konto eingerichtet. Oseyro greift nur auf die bei der Einwilligung angezeigten und für die aktivierte Funktion erforderlichen Daten zu.'], bullets:['Kalender: Kalenderlisten, ausgewählte Termine, Titel, Beschreibung, Ort, Teilnehmer, Zeit und Status; Erstellen beziehungsweise Aktualisieren geschäftlicher Termine im ausdrücklich ausgewählten Zielkalender.', 'Google Meet: Erstellen eines Besprechungsraums nur auf ausdrückliche Aktion des Benutzers.', 'Google-Postfach: Bei aktivierter Postfachverbindung Abruf und Versand der erforderlichen E-Mail-Daten über Google sowie Verarbeitung der zugehörigen Anhänge.', 'Kontoinformationen: technische Google-Kennung und E-Mail-Adresse zur eindeutigen Zuordnung der Verbindung.'] },
    { heading:'6. Verwendung und Schutz von Google-Daten', paragraphs:['Google-Nutzerdaten werden ausschließlich bereitgestellt, um die vom Benutzer aktivierten Kalender-, Besprechungs- und Postfachfunktionen zu erbringen. Sie werden nicht verkauft, nicht für Werbung verwendet und nicht zum Training allgemeiner KI-Modelle genutzt.', 'OAuth-Zugriffstoken werden zweckgebunden, verschlüsselt und getrennt von den eigentlichen Anwendungsdaten gespeichert. Inhalte werden nur an beauftragte Infrastruktur- oder Unterauftragnehmer übermittelt, soweit dies zur Bereitstellung der gewählten Funktion erforderlich und datenschutzrechtlich abgesichert ist. Ein menschlicher Zugriff erfolgt nur bei ausdrücklicher Berechtigung, zur Sicherheit, Fehlerbehebung oder aufgrund gesetzlicher Verpflichtung.', 'Die Verwendung von über Google APIs erhaltenen Informationen erfolgt unter Beachtung der Google API Services User Data Policy einschließlich der Limited-Use-Anforderungen.'] },
    { heading:'7. Speicherdauer und Löschung', paragraphs:['Wir speichern personenbezogene Daten nur so lange, wie sie für den jeweiligen Zweck, zur Vertragserfüllung, Sicherheit oder aufgrund gesetzlicher Pflichten benötigt werden. Kundenbezogene Fristen können durch den Betreiber der jeweiligen Oseyro-Umgebung festgelegt werden.', 'Beim Trennen einer Google-Verbindung werden neue Zugriffe beendet und die zugehörigen Token gelöscht. Beim Löschen eines persönlichen privaten Postfachs werden dessen ausschließlich private Nachrichten, Rohdaten, Metadaten, Entwürfe, Anhänge und Ausgänge gelöscht. Inhalte, die zuvor bewusst in einen öffentlichen Ticketbereich übernommen wurden, sowie notwendige minimale Auditnachweise können entsprechend der geltenden Aufbewahrung fortbestehen. Weitere Einzelheiten finden Sie unter „Daten löschen“.'] },
    { heading:'8. Empfänger und Übermittlungen', paragraphs:['Wir setzen sorgfältig ausgewählte Anbieter für Hosting, Kommunikation, Sicherheit und gegebenenfalls die vom Kunden aktivierten Integrationen ein. Mit Auftragsverarbeitern bestehen die erforderlichen Verträge. Übermittlungen außerhalb des Europäischen Wirtschaftsraums erfolgen nur bei geeigneter Rechtsgrundlage und geeigneten Garantien.'] },
    { heading:'9. Ihre Rechte', paragraphs:['Sie haben nach Maßgabe der gesetzlichen Voraussetzungen das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie auf Widerruf einer Einwilligung für die Zukunft. Sie können sich hierzu an info@xsigns.de wenden.', 'Sie haben außerdem das Recht auf Beschwerde bei einer Datenschutzaufsichtsbehörde. Zuständig ist insbesondere die Landesbeauftragte für den Datenschutz Niedersachsen, Prinzenstraße 5, 30159 Hannover.'] },
  ]},
  privacyEn: { language:'en', label:'Privacy', title:'Privacy policy', intro:'This policy explains in plain language which data Oseyro processes and how you can exercise your rights.', updated:'Last updated: September 2026', alternateHref:'/datenschutz', alternateLabel:'DE', sections:[
    { heading:'1. Controller', paragraphs:['The controller under the General Data Protection Regulation is:', 'Xsigns GmbH & Co. KG · Clärenore-Stinnes-Straße 15 · 27283 Verden (Aller) · Germany', 'Email: info@xsigns.de · Phone: +49 4231 9033900'] },
    { heading:'2. Visiting this website', paragraphs:['When you visit oseyro.com, our hosting system processes technically necessary log data. This may include your IP address, time, requested address, transferred volume, referrer, browser and operating system. We use it to provide a secure and stable website under Art. 6(1)(f) GDPR.', 'The public website currently uses no analytics or advertising services and sets no marketing cookies. Technically necessary delivery and security functions remain unaffected.'] },
    { heading:'3. Contacting us', paragraphs:['If you contact us by email, we process your contact details and message to respond. Depending on your request, the legal basis is Art. 6(1)(b) or (f) GDPR.'] },
    { heading:'4. Using Oseyro', paragraphs:['When you use an Oseyro environment, we process account, organization, communication and usage data needed for sign-in, customer service, tasks, calendars, collaboration, security and auditability. The customer operating the environment determines which content is processed. Xsigns generally processes this data on that customer’s documented instructions.', 'Role-based permissions limit access. Private areas, personal mailboxes and private calendar details are only shown in full to authorized users.'] },
    { heading:'5. Google user data', paragraphs:['Connecting Google is optional and is performed individually by each user for their own Google Account. Oseyro only accesses the data shown on the consent screen and required for the feature the user enables.'], bullets:['Calendar: calendar lists and selected event title, description, location, attendees, time and status; creation or updates of business events in the expressly selected target calendar.', 'Google Meet: creation of a meeting space only when expressly requested by the user.', 'Google mailbox: when enabled, retrieval and delivery of required email data and related attachments through Google.', 'Account information: technical Google identifier and email address used to bind the connection to the correct user.'] },
    { heading:'6. Use and protection of Google data', paragraphs:['Google user data is used solely to provide the calendar, meeting and mailbox features enabled by the user. It is not sold, used for advertising or used to train general-purpose AI models.', 'OAuth access tokens are purpose-bound, encrypted and stored separately from application content. Data is shared only with contracted infrastructure providers or subprocessors where necessary to provide the selected function and covered by appropriate data protection safeguards. Human access occurs only with authorization, for security, troubleshooting or legal obligations.', 'Our use of information received from Google APIs complies with the Google API Services User Data Policy, including its Limited Use requirements.'] },
    { heading:'7. Retention and deletion', paragraphs:['We retain personal data only while needed for its purpose, the contract, security or legal obligations. The operator of an Oseyro environment may define customer-specific retention periods.', 'Disconnecting Google ends new access and deletes the associated tokens. Deleting a private personal mailbox removes all mailbox-only private messages, raw data, metadata, drafts, attachments and outgoing messages. Content previously and intentionally transferred into a public ticket area and necessary minimal audit records may remain under applicable retention rules. See “Delete data” for details.'] },
    { heading:'8. Recipients and transfers', paragraphs:['We use carefully selected providers for hosting, communications, security and integrations enabled by customers. Required data-processing agreements are in place. Transfers outside the European Economic Area occur only with an appropriate legal basis and safeguards.'] },
    { heading:'9. Your rights', paragraphs:['Subject to legal conditions, you may request access, correction, deletion, restriction, portability or object to processing, and withdraw consent for the future. Contact info@xsigns.de.', 'You may also lodge a complaint with a data protection authority. The competent authority is in particular the State Commissioner for Data Protection of Lower Saxony, Prinzenstraße 5, 30159 Hanover, Germany.'] },
  ]},
  termsDe: { language:'de', label:'Rechtliches', title:'Nutzungsbedingungen', intro:'Grundregeln für die Nutzung von Oseyro und der öffentlichen Website.', updated:'Stand: September 2026', alternateHref:'/en/terms', alternateLabel:'EN', sections:[operatorDe,
    { heading:'1. Geltungsbereich', paragraphs:['Diese Bedingungen gelten für die öffentliche Oseyro-Website und ergänzend für die Nutzung bereitgestellter Oseyro-Dienste. Für zahlende Kunden gehen individuelle Verträge und Vereinbarungen zur Auftragsverarbeitung vor.'] },
    { heading:'2. Konten und Berechtigungen', paragraphs:['Zugangsdaten sind persönlich zu schützen. Benutzer dürfen nur auf Daten und Funktionen zugreifen, für die sie berechtigt sind. Der jeweilige Kunde verwaltet seine Benutzer, Rollen und Inhalte.'] },
    { heading:'3. Zulässige Nutzung', paragraphs:['Oseyro darf nicht rechtswidrig, missbräuchlich, zur Umgehung von Sicherheitsmaßnahmen oder zur Beeinträchtigung anderer Systeme genutzt werden. Hochgeladene Inhalte dürfen keine Rechte Dritter verletzen.'] },
    { heading:'4. Integrationen', paragraphs:['Optionale Dienste wie Google werden erst nach ausdrücklicher Verbindung durch den Benutzer aktiviert. Es gelten ergänzend die Bedingungen des jeweiligen Drittanbieters. Eine Verbindung kann jederzeit getrennt werden.'] },
    { heading:'5. Verfügbarkeit und Änderungen', paragraphs:['Wir entwickeln Oseyro fortlaufend weiter. Einzelne Funktionen können geändert werden, soweit der vertraglich vereinbarte Kern erhalten bleibt. Vereinbarte Verfügbarkeiten und Supportleistungen ergeben sich aus dem jeweiligen Kundenvertrag.'] },
    { heading:'6. Rechte und Haftung', paragraphs:['Oseyro, Gestaltung, Software und Inhalte sind rechtlich geschützt. Die Haftung richtet sich nach den zwingenden gesetzlichen Vorschriften und den im jeweiligen Kundenvertrag vereinbarten Regelungen.'] },
  ]},
  termsEn: { language:'en', label:'Legal', title:'Terms of service', intro:'Basic rules for using Oseyro and its public website.', updated:'Last updated: September 2026', alternateHref:'/nutzungsbedingungen', alternateLabel:'DE', sections:[operatorEn,
    { heading:'1. Scope', paragraphs:['These terms apply to the public Oseyro website and, additionally, to provided Oseyro services. Individual customer contracts and data-processing agreements take precedence for paying customers.'] },
    { heading:'2. Accounts and permissions', paragraphs:['Credentials must be kept personal and secure. Users may only access data and functions they are authorized to use. Each customer manages its users, roles and content.'] },
    { heading:'3. Acceptable use', paragraphs:['Oseyro must not be used unlawfully, abusively, to circumvent security measures or to impair other systems. Uploaded content must not infringe third-party rights.'] },
    { heading:'4. Integrations', paragraphs:['Optional services such as Google are enabled only after a user expressly connects them. The third party’s additional terms apply. A connection can be removed at any time.'] },
    { heading:'5. Availability and changes', paragraphs:['We continuously improve Oseyro. Features may change as long as the contractually agreed core remains available. Agreed availability and support commitments are set out in the applicable customer contract.'] },
    { heading:'6. Rights and liability', paragraphs:['Oseyro, its design, software and content are legally protected. Liability is governed by mandatory law and the provisions agreed in the applicable customer contract.'] },
  ]},
  supportDe: { language:'de', label:'Hilfe', title:'Support', intro:'Wir helfen bei Fragen zu Oseyro, Ihrem Konto oder einer verbundenen Integration.', updated:'Kontakt', alternateHref:'/en/support', alternateLabel:'EN', sections:[
    { heading:'So erreichen Sie uns', paragraphs:['E-Mail: info@xsigns.de', 'Telefon: +49 4231 9033900', 'Bitte nennen Sie bei technischen Anfragen Ihre Oseyro-Umgebung und beschreiben Sie das Verhalten möglichst genau. Senden Sie keine Passwörter oder Zugriffstoken.'] },
    { heading:'Datenschutz und Datenlöschung', paragraphs:['Datenschutzanfragen können Sie ebenfalls an info@xsigns.de richten. Für die Trennung verbundener Google-Konten und die Löschung von Daten finden Sie eine eigene Anleitung unter „Daten löschen“.'] },
  ]},
  supportEn: { language:'en', label:'Help', title:'Support', intro:'We help with questions about Oseyro, your account or a connected integration.', updated:'Contact', alternateHref:'/support', alternateLabel:'DE', sections:[
    { heading:'Contact us', paragraphs:['Email: info@xsigns.de', 'Phone: +49 4231 9033900', 'For technical requests, include your Oseyro environment and describe what happened. Never send passwords or access tokens.'] },
    { heading:'Privacy and deletion', paragraphs:['You may also send privacy requests to info@xsigns.de. See “Delete data” for instructions on disconnecting Google Accounts and deleting data.'] },
  ]},
  deletionDe: { language:'de', label:'Datenschutz', title:'Daten löschen', intro:'So trennen Sie verbundene Dienste und beantragen die Löschung Ihrer Daten.', updated:'Stand: September 2026', alternateHref:'/en/data-deletion', alternateLabel:'EN', sections:[
    { heading:'Google-Verbindung selbst trennen', paragraphs:['Öffnen Sie in Oseyro Ihre persönlichen Einstellungen und wählen Sie bei der betreffenden Google-Kalender-, Meet- oder Postfachverbindung „Trennen“. Oseyro beendet anschließend den Zugriff und entfernt die gespeicherten OAuth-Token.', 'Zusätzlich können Sie Oseyros Zugriff jederzeit in den Sicherheitseinstellungen Ihres Google-Kontos unter „Verbindungen zu Drittanbieter-Apps“ widerrufen.'] },
    { heading:'Löschung beantragen', paragraphs:['Senden Sie Ihre Anfrage von der mit Ihrem Oseyro-Konto verbundenen E-Mail-Adresse an info@xsigns.de. Verwenden Sie den Betreff „Oseyro – Datenlöschung“ und nennen Sie Ihre Oseyro-Umgebung. Wir prüfen Ihre Identität, bestätigen den Umfang und informieren Sie über die Durchführung oder gesetzlich notwendige Aufbewahrung.'] },
    { heading:'Persönliches privates Postfach', paragraphs:['Beim Löschen eines persönlichen privaten Postfachs werden alle ausschließlich postfachbezogenen privaten Nachrichten, Rohdaten, Metadaten, Delegationen, Ausgänge, Entwürfe und Anhänge gelöscht. Inhalte, die bewusst in einen öffentlichen Ticketbereich übernommen wurden, und der dafür notwendige minimale Auditnachweis bleiben entsprechend der dort geltenden Aufbewahrung erhalten; die private Ursprungskopie wird gelöscht.'] },
  ]},
  deletionEn: { language:'en', label:'Privacy', title:'Delete your data', intro:'How to disconnect services and request deletion of your data.', updated:'Last updated: September 2026', alternateHref:'/datenloeschung', alternateLabel:'DE', sections:[
    { heading:'Disconnect Google yourself', paragraphs:['Open your personal settings in Oseyro and choose “Disconnect” for the relevant Google Calendar, Meet or mailbox connection. Oseyro then stops access and removes the stored OAuth tokens.', 'You can additionally revoke Oseyro at any time in your Google Account security settings under third-party app connections.'] },
    { heading:'Request deletion', paragraphs:['Email info@xsigns.de from the address linked to your Oseyro account. Use the subject “Oseyro – data deletion” and name your Oseyro environment. We verify your identity, confirm the scope and tell you when deletion is complete or which information must legally be retained.'] },
    { heading:'Private personal mailbox', paragraphs:['Deleting a private personal mailbox removes all mailbox-only private messages, raw data, metadata, delegations, outgoing messages, drafts and attachments. Content intentionally moved into a public ticket area and the necessary minimal audit record remain under the applicable retention rules; the private source copy is deleted.'] },
  ]},
};
