export type Language = 'de' | 'en';

export const siteContent = {
  de: {
    alternateHref: '/en', alternateLabel: 'EN',
    navigation: [{ label: 'Produkt', href: '#produkt' }, { label: 'Funktionen', href: '#funktionen' }, { label: 'Sicherheit', href: '#sicherheit' }],
    eyebrow: 'Kundenservice · Aufgaben · Kalender',
    headline: 'Service, der sich selbst organisiert.',
    intro: 'Oseyro verbindet Kundenanfragen, Wissen, Aufgaben und Termine in einem ruhigen Arbeitsbereich – damit Teams weniger verwalten und mehr lösen.',
    primaryAction: 'Oseyro entdecken', secondaryAction: 'Gespräch vereinbaren',
    trust: ['In Deutschland betrieben', 'Datenschutz im Kern', 'Für Menschen und KI gemacht'],
    workspaceLabel: 'Gemeinsamer Arbeitsbereich', ticketLabel: 'Neue Kundenanfrage',
    ticketTitle: 'Rückfrage zur Reservierung', ticketMeta: 'Heute, 09:42 · E-Mail',
    ticketCopy: 'Können wir die Anreise auf Freitag verschieben und einen späteren Check-in vereinbaren?',
    assistantLabel: 'Oseyro Vorschlag',
    assistantCopy: 'Die Buchung ist flexibel. Eine passende Antwort und zwei freie Zeitfenster sind vorbereitet.',
    actionLabel: 'Antwort prüfen',
    stats: [['Ein Eingang', 'für E-Mail, Portal, Telefon und Partner'], ['Ein Kontext', 'für Service, Aufgaben, Wissen und Termine'], ['Klare Kontrolle', 'durch Rollen, Freigaben und Audit']],
    sectionEyebrow: 'Alles in einem ruhigen Fluss',
    sectionTitle: 'Vom ersten Kontakt bis zur erledigten Aufgabe.',
    sectionIntro: 'Oseyro hält Gespräche, Verantwortung und Zeitplanung zusammen. Jede Person sieht genau das, was sie für den nächsten guten Schritt braucht.',
    features: [
      ['Omnichannel-Service', 'E-Mail, Portal, Telefon und Partnerdialoge laufen als nachvollziehbare Vorgänge in einem gemeinsamen Eingang zusammen.'],
      ['Aufgaben, die Kontext behalten', 'Aus Kundennachrichten entstehen planbare Aufgaben mit Verantwortlichen, Kommentaren, Erwähnungen und Wiedervorlagen.'],
      ['Kalender für echte Teamarbeit', 'Eigene Termine, Aufgabenblöcke, Räume und Verfügbarkeiten werden gemeinsam planbar – private Inhalte bleiben privat.'],
      ['Wissen im richtigen Moment', 'Versioniertes Teamwissen und passende Artikel erscheinen dort, wo eine Anfrage gerade gelöst wird.'],
      ['KI mit menschlicher Kontrolle', 'Oseyro fasst zusammen, ordnet ein und bereitet Antworten vor. Freigaben und Grenzen bleiben sichtbar.'],
      ['Mandantenfähig gedacht', 'Getrennte Kundenumgebungen, Rollen und Audits schaffen eine belastbare Grundlage für wachsende Organisationen.'],
    ],
    securityEyebrow: 'Souverän und nachvollziehbar',
    securityTitle: 'Ihre Daten bleiben unter Kontrolle.',
    securityCopy: 'Oseyro wird in Deutschland betrieben und verbindet moderne Automatisierung mit klaren Berechtigungen, Verschlüsselung und vollständiger Nachvollziehbarkeit.',
    securityPoints: ['Rollenbasierte Zugriffe und private Bereiche', 'Verschlüsselte Verbindungen und sensible Zugangsdaten', 'Auditierbare Änderungen und kontrollierte Freigaben', 'Getrennte Kundenumgebungen und eigene Aufbewahrung'],
    googleTitle: 'Google Kalender – verbunden, nicht vermischt.',
    googleCopy: 'Ausgewählte Kalender können synchronisiert werden. Eigentümer sehen ihre vollständigen privaten Termine; für andere bleibt ausschließlich die Belegung sichtbar.',
    closingTitle: 'Mehr Ruhe im Service. Mehr Klarheit im Team.',
    closingCopy: 'Oseyro entsteht für Organisationen, die Service nicht nur beantworten, sondern zuverlässig organisieren wollen.',
    footer: { product: 'Produkt', privacy: 'Datenschutz', imprint: 'Impressum', terms: 'Nutzungsbedingungen', support: 'Support', deletion: 'Daten löschen' },
  },
  en: {
    alternateHref: '/', alternateLabel: 'DE',
    navigation: [{ label: 'Product', href: '#product' }, { label: 'Features', href: '#features' }, { label: 'Security', href: '#security' }],
    eyebrow: 'Customer service · Tasks · Calendar',
    headline: 'Service that organizes itself.',
    intro: 'Oseyro brings customer conversations, knowledge, tasks and schedules into one calm workspace — so teams spend less time managing and more time solving.',
    primaryAction: 'Discover Oseyro', secondaryAction: 'Book a conversation',
    trust: ['Hosted in Germany', 'Privacy at its core', 'Built for humans and AI'],
    workspaceLabel: 'Shared workspace', ticketLabel: 'New customer request',
    ticketTitle: 'Question about a reservation', ticketMeta: 'Today, 09:42 · Email',
    ticketCopy: 'Can we move our arrival to Friday and arrange a later check-in?',
    assistantLabel: 'Oseyro suggestion',
    assistantCopy: 'The booking is flexible. A suitable reply and two available time slots are ready.',
    actionLabel: 'Review reply',
    stats: [['One inbox', 'for email, portal, phone and partners'], ['One context', 'for service, tasks, knowledge and meetings'], ['Clear control', 'through roles, approvals and audit trails']],
    sectionEyebrow: 'Everything in one calm flow',
    sectionTitle: 'From first contact to finished work.',
    sectionIntro: 'Oseyro keeps conversations, ownership and schedules together. Everyone sees exactly what they need to make the next good decision.',
    features: [
      ['Omnichannel service', 'Email, portal, phone and partner conversations become traceable cases in one shared inbox.'],
      ['Tasks that keep their context', 'Turn customer messages into scheduled work with owners, comments, mentions and reminders.'],
      ['A calendar built for teams', 'Plan meetings, task blocks, rooms and availability together while private details stay private.'],
      ['Knowledge at the right moment', 'Versioned team knowledge and relevant articles appear exactly where a request is being solved.'],
      ['AI with human control', 'Oseyro summarizes, classifies and prepares replies while approvals and boundaries stay visible.'],
      ['Ready for multiple organizations', 'Isolated customer environments, roles and audit trails form a dependable foundation for growth.'],
    ],
    securityEyebrow: 'Sovereign and accountable',
    securityTitle: 'Your data stays under control.',
    securityCopy: 'Oseyro is hosted in Germany and combines modern automation with clear permissions, encryption and a complete audit trail.',
    securityPoints: ['Role-based access and private areas', 'Encrypted connections and sensitive credentials', 'Auditable changes and controlled approvals', 'Isolated customer environments and retention policies'],
    googleTitle: 'Google Calendar — connected, never mixed up.',
    googleCopy: 'Selected calendars can be synchronized. Owners see the full details of their private events; everyone else sees availability only.',
    closingTitle: 'Calmer service. Clearer teamwork.',
    closingCopy: 'Oseyro is being built for organizations that want to do more than answer service requests — they want to organize them reliably.',
    footer: { product: 'Product', privacy: 'Privacy', imprint: 'Imprint', terms: 'Terms', support: 'Support', deletion: 'Delete data' },
  },
} as const;
